name: Compilation 32-bits (Compatible)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Récupération du code
      uses: actions/checkout@v4

    - name: 2. Installation de Python 3.9 (32-bits Stable)
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # <--- CHANGEMENT ICI (Plus compatible)
        architecture: 'x86'   # Force le mode 32-bits

    - name: 3. Mise à jour de pip
      run: python -m pip install --upgrade pip

    - name: 4. Installation des modules
      # On installe une version spécifique de matplotlib compatible 32-bits
      run: |
        pip install customtkinter pyinstaller pywin32
        pip install "matplotlib<3.8" 

    - name: 5. Création du fichier EXE
      run: |
        pyinstaller --noconsole --onefile --collect-all customtkinter --name "stock_expert_1" stock_expert.py

    - name: 6. Sauvegarde du résultat
      uses: actions/upload-artifact@v4
      with:
        name: LOGICIEL_COMPATIBLE_32BIT
        path: dist/stock_expert_1.exe
