name: Compilation 32-bits (Compatible)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# INDISPENSABLE : Donne l'autorisation à GitHub Actions de créer une Release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Récupération du code
      uses: actions/checkout@v4

    - name: 2. Lecture de la version depuis version.txt
      id: get_version
      run: |
        $VER = Get-Content version.txt
        echo "VERSION=$VER" >> $env:GITHUB_ENV

    - name: 3. Installation de Python 3.9 (32-bits Stable)
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x86'

    - name: 4. Mise à jour de pip
      run: python -m pip install --upgrade pip

    - name: 5. Installation des modules
      run: |
        pip install customtkinter pyinstaller pywin32
        pip install "matplotlib<3.8" 

    - name: 6. Création du fichier EXE
      run: |
        pyinstaller --noconsole --onefile --collect-all customtkinter --name "stock_expert_1" stock_expert.py

    - name: 7. Création de la Release automatique !
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Mise à jour ${{ env.VERSION }}
        files: dist/stock_expert_1.exe
        make_latest: true
